#!/bin/bash
FILE="/etc/hosts"
if grep -q "127.0.0.1 youtube.com" $FILE; then
    echo ''
else

    sed -i "" -e $'/127.0.0.1	localhost/a\\\n'"127.0.0.1 youtube.com" $FILE
    sed -i "" -e $'/127.0.0.1 youtube.com/a\\\n'"127.0.0.1 www.youtube.com" $FILE
    echo "Productive"
fi